<?php

/**
 * @file
 * Provides a service for (de)serializing data to/from formats such as JSON and XML.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jsonapi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.jsonapi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output;
  }
}
